[project]
name = "chuntfm-schedule-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.122.0",
    "python-dateutil>=2.9.0.post0",
    "sqlalchemy>=2.0.44",
    "uvicorn>=0.38.0",
]
